### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by phamminhtnl** [callisto-jovy/viddroid_desktop#1]
Please tell me how to use repo ?

**Comment by callisto-jovy** [comment]
You could clone the repo yourself and run a flutter build. In any case, I will soon release an alpha version, which you could then download if you wish.

**Comment by callisto-jovy** [comment]
There is now a download link for the alpha: https://github.com/callisto-jovy/viddroid_desktop/releases/tag/Alpha
