### ISSUE TITLE
api key 

### ISSUE THREAD

**Issue by AmirHosseinAsa** [callisto-jovy/viddroid_desktop#3]
How can I get an API key?

**Comment by callisto-jovy** [comment]
If you like to compile the project yourself, you can obtain a TMDB api key from [here](https://developer.themoviedb.org/). You will have to register a developer account, which will allow you to retrieve your custom API key. Then you are able to just add a new file named API (you probably saw that in the helper for TMDB [[here](https://github.com/callisto-jovy/viddroid_desktop/blob/master/lib/util/movie_provider/the_movie_db.dart)) with your key. Feel free to reply to this thread if you have anymore questions.

**Comment by callisto-jovy** [comment]
As there have been no further questions, I will close this question now. Feel free to open a new one or message me if you have any follow-up questions.
